### PR TITLE
Implemented #22 withSender() function

### PR DESCRIPTION
**Pull request by grosch**
#22

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @grosch !

Could you squash these into a single commit? Then, I'll merge :clap:

**Comment by jessesquires** [comment]
@grosch — Looks like we squashed one commit (went from 2 to 3). Let me know if you need help! :smile: 

Might be easier to do a rebase of f979b57 on `develop`. Then, if needed, you can `git push -f` to force an update of the branch

**Comment by grosch** [comment]
Yah, I need help.  My general format is:

git clone ….
git co -b issue_22_feature
edit code
git commit ...
git co develop
git merge issue_22_feature
git branch -d issue_22_feature
git push

When I do the merge, it always forces me to give a new commit message, which pisses me off to no end.

**Comment by jessesquires** [comment]
:smile: 

Assuming the first `git clone` gets the latest on `develop`, this should be good:

```
git clone <...>
git co -b issue_22_feature
// edit code
git commit <...>
git push
```

If not, then after the first clone `git pull upstream develop` (assuming `upstream` points to the original repo, not your fork — which is usually `origin`)

In other words, `git checkout develop` and make sure you have all the latest changes, **then** `git co -b <new branch>`

---

Alternatively, with your current state, you can revert this second commit, then rebase. Easiest with roughly the following:

``` bash
# on branch issue_22_feature
git reset --hard HEAD^ # undo the most recent commit, should leave you at 38cb5b6 
git rebase develop # rebase on top of develop, assuming your develop is up-to-date
git push -f # forces update on the remote branch
```

**Comment by grosch** [comment]
> git clone <...>
> git co -b issue_22_feature
> // edit code
> git commit <...>
> git push

This would push it as the issue_22_feature branch, not the develop branch.  Would that be want you want?

**Comment by jessesquires** [comment]
Correct! :smile:

**Comment by jessesquires** [comment]
@grosch -- actually, it looks like your first commit (f979b57) is fine (no conflicts).

On your branch for this PR, the following should fix this up:

``` bash
git reset --hard HEAD^
git push -f
```

**Comment by grosch** [comment]
Grr.  Argh.  I ran those two commands.  Now the code is gone ;(

**Comment by jessesquires** [comment]
Ugh sorry! I misread the order because of how github renders the web UI. I thought the develop merge was 2nd, but it was the first commit.

**Comment by grosch** [comment]
This time you get to implement it :)

**Comment by jessesquires** [comment]
Lol sorry @grosch!

**Pull request closed without merging**
