### PR TITLE
Issue 28 feature

### PR DESCRIPTION
**Pull request by grosch**
Implements #28

### CODE REVIEW

**Comment by grosch** [comment]
You know you want it...

**Comment by jessesquires** [comment]
lol :laughing: 

Thanks @grosch ! :smile: 

A few notes:
- :+1: for the `Cocoa*` additions. For the others, I'm not sure these should be included in the library. Let's merge only the `Cocoa*` typealiases for now.
- Really hate to block on this, but the commit history is particularly dirty here, looks like there are 3 unrelated commits? :grin:

**Comment by grosch** [comment]
OK, so I hate github, and I never use it for anything but you.  What I really need is for your contributing page to have explicit instructions.  It needs to start with the "I had my own fork of your stuff.  So first I need to update to make mine look exactly like you, then I do my code, then I do thing X to make it look the way you want, and then I submit the pull request"

**Comment by jessesquires** [comment]
> OK, so I hate github

:laughing: I'm sorry!

img

> What I really need is for your contributing page to have explicit instructions.

I'll work on this! :+1: 

---

So, the merging/rebasing on develop is technically optional. This really only needs to happen if there are conflicts. So maybe try this flow instead:
1. Make your changes
2. Submit a PR

If there are no conflicts, we can merge and you don't have to do anything else special. If there are conflicts, then GitHub will note this and we can handle it. 

This shouldn't have any conflicts. Looks like all we need is 08083e52e6bf2894b12c73ba25edcd12213d823e. If you undo the previous commits and update the branch, we should be good.

Also, sometimes it's just easier to make a new branch, copy-pasta :spaghetti: your changes and make a fresh commit, then submit the PR :smile:

**Comment by jessesquires** [comment]
Thanks @grosch ! :smile: 

GitHub now squashes commits for PRs, so :tada: :tada:

**Pull request merged**
